image: alpine:latest

pages:
  stage: deploy
  script:
  - mkdir public
  - cp -r dashboard.css dashboard.js index.html Leaflet.Icon.Glyph.js img public/
  artifacts:
    paths:
    - public
  only:
  - master
